# Docker Compose configuration for PSOR project
# Modernized: explicit image tags for all plugins

services:
  orchestrator:
    build: ./orchestrator
    working_dir: /app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./playbooks:/app/playbooks:ro
      - ./reports:/app/reports:rw
      - ./plugins:/app/plugins:ro

  plugin-python-revoke-key:
    build:
      context: ./plugins/python-sdk
      dockerfile: revoke-iam-key/Dockerfile
    image: psor_platform_plugin-python-revoke-key

  plugin-java-block-ip:
    build:
      context: ./plugins/java-sdk
      dockerfile: block-ip-address/Dockerfile
    image: psor_platform_plugin-java-block-ip

  plugin-rust-isolate-endpoint:
    build:
      context: ./plugins/rust-sdk
      dockerfile: isolate-endpoint/Dockerfile
    image: psor_platform_plugin-rust-isolate-endpoint

  plugin-java-unblock-ip:
    build:
      context: ./plugins/java-sdk
      dockerfile: unblock-ip-address/Dockerfile
    image: psor_platform_plugin-java-unblock-ip

  plugin-rust-unisolate-endpoint:
    build:
      context: ./plugins/rust-sdk
      dockerfile: unisolate-endpoint/Dockerfile
    image: psor_platform_plugin-rust-unisolate-endpoint

  # Optional JS plugin
  # plugin-js-log-message:
  #   build:
  #     context: ./plugins/js-sdk
  #     dockerfile: log-message/Dockerfile
  #   image: psor_platform_plugin-js-log-message
